import { Open_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`flex ${openSans.className}`}>
        <Sidebar />
        {/* Ensure all content is pushed to the right of the sidebar */}
        <div className="ml-64 flex-1 bg-gray-100">
          {children}
        </div>
      </body>
    </html>
  );
}
